# -*- coding: utf-8 -*-
"""P1-Text generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJ6XOgwUplC4yVq35WHvcLobkRVhx1ct
"""

!pip install transformers torch

from transformers import pipeline
#loading gpt model
generator=pipeline(
    "text-generation",
    model="gpt2"
 )
#input prompt
prompt="Artificial Intelligence in finance will"
#generating output
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])