# -*- coding: utf-8 -*-
"""P2-Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkEv8WifEjwKooiOVFj6vp_Ko805Hvu6
"""

!pip install sentence-transformers
from sentence_transformers import SentenceTransformer,util

#loading model
model=SentenceTransformer('all-MiniLM-L6-v2')
#take input promt
text1=input("Enter text1: ")
text2=input("Enter text2: ")
#convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n Similarity score: ",round(float(similarity),2))
if similarity> 0.75:
  print("Similarity level:High")
elif similarity> 0.4:
  print("Similarity level:Medium")
else:
    print("Similarity level:low")