# -*- coding: utf-8 -*-
"""P3-Product review summarizer project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4uMnT32LQPww8U_JSuFrDkjYZZhe4I8
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#load sentiment analysis model
sentiment=pipeline("sentiment-analysis")
#sample producr review
reviews="""
The laptop starts quickly and works smoothly for daily tasks.
the    screen quality is clear and good for watching  videos.
Battery backup  is   average    and   needs  charging  often.
The   fan   makes  noise  when many apps are running overall.
it   is  a  good  laptop  students   but      for     gaming.
"""

sentences=reviews.split(".")
pros=[]
cons=[]
for s in sentences:
  s=s.strip()
  if s=="":
    continue
  result=sentiment(s)
  if result[0]["label"]=="POSITIVE":
    pros.append(s)
  elif result[0]["label"]=="NEGATIVE":
    cons.append(s)
pros=pros[:2]
cons=cons[:2]
df=pd.DataFrame({
    "pros":pros,
    "cons":cons
})
df