# -*- coding: utf-8 -*-
"""P4-Timetable generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwLifY945RkLK77H84K53D3VDpPi09HS
"""

import pandas as pd
import random
print("TIMETABLE  GENERATIOR\n")
#user inputs
subjects_input=input("Enter subjects (comma separated): ")
days_input=input("Enter days (comma separated): ")
periods_per_day=int(input("Enter number of periods per day: "))


#process inputs
subjects=[s.strip() for s in subjects_input.split(',') if s.strip()]
days=[d.strip() for d in days_input.split(",") if d.strip()]

#validation
if len(subjects)== 0 or len(days)==0 or periods_per_day<=0:
  print("Invalid input. Please try again.")
else:
    timetable={}
    for day in days:
      timetable[day]=random.choices(subjects, k=periods_per_day)


#CREATE DATAFRAME
df=pd.DataFrame(timetable)
df.index=[f"period {i+1}" for i in range(periods_per_day)]
print("\nTimetable Generated successfuly\n")
display(df)
#save timetable
df.to_csv("timetable.csv")
print("\nTimetable saved as timetable.csv")